# Travis-CI Configuration File

# Whitelist
branches:
  only:
    - master
    
language: python    # this works for Linux but is an error on macOS or Windows
jobs:
  include:
#-----------------------------------------------------------------------------#
#                                    MACOS                                    #
#-----------------------------------------------------------------------------#
# macOS xcode9.4 = Python 3.6.5
# macOS xcode10.2 = Python 3.7.3
# macOS xcode11.2 = Python 3.7.4?
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

#-----------------------------------------------------------------------------#
#                                    LINUX                                    #
#-----------------------------------------------------------------------------#
    - name: "Python 3.4 on Xenial Linux"
      python: 3.4
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7.4 on Xenial Linux"
      python: 3.7.4        # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8


before_install:
  - python3 --version

# command to install dependencies
install:
  - pip3 install --upgrade pip       # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt  # install repo specific modules


# command to run tests
script:
  # Fetch records
  - src/NCBImeta.py --flat --config example/config.yaml
  # Database Annotation
  - src/NCBImeta_AnnotateReplace.py --database example/yersinia_pestis_db.sqlite --annotfile example/annot.txt --table BioSample
  - src/NCBImeta_AnnotateConcatenate.py --database example/yersinia_pestis_db.sqlite --annotfile example/annot.txt --table BioSample
  # Database table join
  - src/NCBImeta_Join.py --database example/yersinia_pestis_db.sqlite --anchor BioSample --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession BioSampleAccessionSecondary BioSampleBioProjectAccession"
  # Database export
  - src/NCBImeta_Export.py --database example/yersinia_pestis_db.sqlite --outputdir example/
