branches:
  only:
  - master
  - /^v.*$/
language: python
jobs:
  include:
  - name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: Python 3.5 on Xenial Linux
    python: 3.5
  - name: Python 3.6 on Xenial Linux
    python: 3.6
  - name: Python 3.7.4 on Xenial Linux
    python: 3.7.4
  - name: Python 3.8 on Xenial Linux
    python: 3.8
before_install:
- python3 --version
install:
- pip3 install --upgrade pip
- pip3 install . -r requirements.txt
- pip3 install codecov==2.0.15 pytest==5.3.1 coverage==4.5.4 pytest-cov==2.8.1
script:
- python3 -m coverage run -m pytest --cov=ncbimeta --cov-report=xml test/test_errors.py
#  test/test_utilities.py test/test_ncbimeta.py test/test_annotateconcatenate.py test/test_annotatereplace.py
#  test/test_join.py test/test_export.py
#- NCBImeta.py --flat --config example/config.yaml
#- NCBImetaAnnotateReplace.py --database example/yersinia_pestis_db.sqlite --annotfile
#  example/annot.txt --table BioSample
#- NCBImetaAnnotateConcatenate.py --database example/yersinia_pestis_db.sqlite --annotfile
#  example/annot.txt --table BioSample
#- NCBImetaJoin.py --database example/yersinia_pestis_db.sqlite --anchor BioSample
#  --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession
#  BioSampleAccessionSecondary BioSampleBioProjectAccession"
#- NCBImetaExport.py --database example/yersinia_pestis_db.sqlite --outputdir example/
after_success:
#- bash < (curl -s https://codecov.io/bash)
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
    program_name=ncbimeta;
    bioconda_recipe=meta.yaml;
    program_ver=`NCBImeta.py --version | cut -d " " -f2 | sed 's/v//g'`;
    program_url=https://github.com/${TRAVIS_REPO_SLUG}/archive/v${program_ver}.tar.gz;
    cd ../ ;
    git clone https://github.com/${GITHUB_USER}/bioconda-recipes.git;
    cd bioconda-recipes/;
    git checkout master;
    git config user.name $GITHUB_USER;
    git config user.email $GITHUB_USER_EMAIL;
    git remote add upstream https://github.com/bioconda/bioconda-recipes.git;
    git pull upstream master;
    git remote rm origin;
    git remote add origin https://${GITHUB_USER}:${GITHUB_API_KEY}@github.com/${GITHUB_USER}/bioconda-recipes.git > /dev/null 2>&1;
    git push -f -q https://${GITHUB_USER}:${GITHUB_API_KEY}@github.com/${GITHUB_USER}/bioconda-recipes master;
    cd recipes/;
    dest_ver=`echo "{% set version = \"${program_ver}"\" %}`;
    src_ver=`grep "set version" ${program_name}/${bioconda_recipe}`;
    dest_sha256=`wget -O- ${program_url} | shasum -a 256 | cut -d " " -f 1`;
    src_sha256=`grep "sha256" ${program_name}/${bioconda_recipe} | sed 's/^ *//g' | cut -d " " -f 2`;
    git config -l;
    git remote -v;
    git branch -a;
    git branch ${program_name}-${program_ver} origin/${program_name}-${program_ver};
    git checkout ${program_name}-${program_ver}
    head ${program_name}/${bioconda_recipe};
    sed -i "s/$src_ver/$dest_ver/g" ${program_name}/${bioconda_recipe};
    sed -i "s/$src_sha256/$dest_sha256/g" ${program_name}/${bioconda_recipe};
    head ${program_name}/${bioconda_recipe};
    cd ../../NCBImeta/;
  fi
deploy:
  provider: pypi
  user: ${GITHUB_USER}
  password:
    secure: yDyygOrB0wtkeYPOVHPYN45waTXdenAC9kBac778/z9TTEYIdXjLTaYEJFkDzQeiH7ykH09OVdpkL6Z+YbzE6oFxuZzEWZ906MX2uT26BUsGIjXa3yIJrMw7aqQC8/Q8wYZBoM2KA/63ur/vxuMfju/Q6lDQvaA14+Nt+u20pyNHFwB/cGGNJdH/wAbgANVQ7QW88fVyUublDo3zONw8VYuLZaTePcMQnglmSva68KhUskDFO6Fz+yCzzBEqiUsbEIXs0etGkq4aPoHDq5esYE/6d/ql2jmhDTRRBrYQsnoCbXIDbafPij85djV3b+TWtoONlW1uDkqUq+22F8dA/nR4QSg8+l3JkKb4cyR5CINC/3JR/AobkwtFcmLcXAiQG5oN5QjqIPuW5X2fcPoQjsoalkDBhpxX0Aj2T9l/h/52++2I5L9N+aWzGb7TrFArGL9nlMsrfz9CK+J6GqUPDMU7v6w/UGJal11k6l3PatAEozbaMpE1iXQwiyiehpE0p4u8dLl3R54Fb+tMwS2xvIol4uRUSFn//aWdPMM2Z5jg5p5w4xiAUBMZR2vM0WIdU6PSfoel4tZlxzH99EOCjpx6CTEhCvpnwfaYkOaHLmFl8zu6lIKRsru6q3hexVSbWqudpOT6RHI3B9JrKPkLbklYsTf0E7M6ehcPsbHLTmE=
  skip_existing: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_PYTHON_VERSION = "3.5"
    tags: true
